### PR TITLE
Fix-Generic-00001a

### PR DESCRIPTION
**Pull request by DennisJensen-OWC**
Okay I have removed the one change in Fix-Generic-00001 that would not compile in FreeNAS 10.  These changes do require a minor change to the make parameters that I were given to me.  The changes area as follows:

make
     DELTAS=4
     MILESTONE=MASTER
     TRAIN=FreeNAS-10-Nightlies
     PROFILE=freenas10
     PRODUCT=FreeNAS
release

Thus if either MILESTONE is not added in which breaks regardless of these changes or if PROFILE is not changed to this current value (freenas10) then the build will not complete successful due to the changes

These changes only affect the following files if there any issues with any other file they can be ignored and overwritten as I did not make changes to them

Makefile
build/config/env.pyd
build/profiles/profile-setting
build/profiles/default/config.pyd → build/profiles/freenas10/config.pyd

The rest of the changes are simply moving the contents as follows:

build/profiles/default/...  →  build/profiles/freenas10/...

Thus other than renaming the default directory to freenas10 these remaining files were not changed.

build/profiles/freenas10/ValidateUpdate
build/profiles/freenas10/env.pyd
build/profiles/freenas10/jail.pyd
build/profiles/freenas10/kernel/DEBUG
build/profiles/freenas10/kernel/FREENAS.amd64
build/profiles/freenas10/packages.pyd
build/profiles/freenas10/packages/base-os/config
build/profiles/freenas10/packages/freebsd-pkgdb/config
build/profiles/freenas10/packages/freebsd-pkgdb/filelist
build/profiles/freenas10/packages/freenas-pkg-tools/config
build/profiles/freenas10/packages/freenasUI/config
build/profiles/freenas10/packages/freenasUI/filelist
build/profiles/freenas10/packages/middleware/config
build/profiles/freenas10/packages/middleware/filelist
build/profiles/freenas10/ports-gui.pyd
build/profiles/freenas10/ports-middleware.pyd
build/profiles/freenas10/ports-system.pyd
build/profiles/freenas10/ports-truenas.pyd
build/profiles/freenas10/ports.pyd
build/profiles/freenas10/repos.pyd

### CODE REVIEW

**Comment by DennisJensen-OWC** [comment]
As noted these conflicts can be fixed by simply moving the current versions of these two files into the new directory and overwriting the files contained within.  Thus simply doing the following overwriting the destination file will fix the issue -- Secondary note the build/profiles/default/... directory and its contents should be deleted when all is said and done -- I did grab like the most recent version of master just a day or two ago when making this pull request so I hope this can be resolved on your end

build/profiles/default/kernel/FREENAS.amd64 → build/profiles/freenas10/kernel/FREENAS.amd64

build/profiles/default/repos.pyd → build/profiles/freenas10/repos.pyd

**Comment by jordanhubbard** [comment]
Hi Dennis.

1. Have you figured out why it’s necessary to set MILESTONE now?  Is this because "default" is gone?  It's certainly nothing you have to do now, and the setting of MASTER does not correlate to anything I can think of - it's not a branch name, or a profile, or ... ?

2. Github won't allow the merging of branches with conflicts - you have to resolve the conflicts first.  Why not simply git mv the files, or remove/add them if that's more appropriate, in the branch?

**Comment by DennisJensen-OWC** [comment]
Okay if you look at the code within  build/config/env.pyd  it basically states that if MILESTONE is not set to something regardless of the Profile being “default” or not then you will get an error.  Not knowing the exact purpose of MILESTONE on your end I assumed it was done this way because MILESTONE was required.   The section of code in question does basically the following:

IF MILESTONE == “MASTER”
     BUILD_TYPE = VERSION.MILESTONE
ELSE
     BUILD_TYPE = MILESTONE

So if MILESTONE is not set to something prior to this point then when it gets to the ELSE clause the code fails because it will not let you assign nothing to BUILD_TYPE (I do not recall the exact error but that was the basic gist of it)  Thus if MILESTONE is not a required element of the Build Process this code should validate that MILESTONE even exists prior to trying to assign it to BUILD_TYPE and I am assuming (looking at this bit of code) that BUILD_TYPE must have a value for later on down the road (and if this is true) then BUILD_TYPE needs some kind of default value assigned to it in case MILESTONE is not needed

**Comment by DennisJensen-OWC** [comment]
Jakub:  Can you jump in here?  This question is past my competence with the freenas-build project. :)

**Comment by jceel** [comment]
Hi Dennis,

BUILD_TYPE should have a global default value of "MASTER" and it's needed by the build process. MILESTONE is not badly needed - it's simply used to construct the VERSION and guess BUILD_TYPE.

**Pull request closed without merging**
