### PR TITLE
Add xen guest utilities to packages

### PR DESCRIPTION
**Pull request by Phlogi**
Since 9.10 (FreeBSD 10) XEN is kernel supported, so the tools should come with the image
https://github.com/freenas/freenas-build/blob/master/build/profiles/freenas9/kernel/FREENAS.amd64#L302

Thanks for your consideration!

### CODE REVIEW

**Comment by amotin** [comment]
Do you know those tools well? Have you used them before?

For some experiments I've installed XenServer 6.5 and those tools on VM. What I see now is that VM indeed reports some information to the host, that is good.  On the other side it seems like XenServer expects more then that, such as support for shutdown, reboot, suspend, etc, and it complains when too simple guest tools don't react on its requests. Don't you think that it can create more problems then solve?

**Comment by jpaetzel** [comment]
The xen-guest-tools aren't useful to FreeNAS.

**Comment by amotin** [comment]
It seems like I was unfair. On more tests shutdown and reboot are working properly, not sure what it was yesterday. I've committed part of your patch, just without explicitly mentioning xen-guest-tools, that is automatically picked up as dependency.

Unfortunately the port version we have now in 2016Q1 ports branch does not support automatic Xen detection and requires xenguest_enable rc.conf variable to be set via WebUI.  I hope we soon update to 2016Q2 branch where this problem is already solved.

**Comment by Phlogi** [comment]
Perfect, I think we can live with that and setting a tunable for enabling it seems fine to me.

**Comment by Phlogi** [comment]
I can confirm that it's correctly implemented in the latest version using the tunable.

**Pull request closed without merging**
