### PR TITLE
Generic 00001b

### PR DESCRIPTION
**Pull request by DennisJensen-OWC**
Removed Conflict -- Removed problematic change -- Hopefully this version can go in without a hitch.

Note however again this requires that the command line parameters be tweaked slightly as "default" has now become "freenas10" and MILESTONE as before requires that it must have a value

make
   DELTAS=4
   MILESTONE=MASTER
   TRAIN=FreeNAS-10-Nightlies
   PROFILE=freenas10
   PRODUCT=FreeNAS
release

### CODE REVIEW

**Comment by jordanhubbard** [comment]
This still has conflicts:
Conflicting files
build/profiles/default/ports-middleware.pyd

**Comment by DennisJensen-OWC** [comment]
Hi Jordan this will be the third time I have had to submit this simple change — when I submitted it the first time I did not understand that you could not handle resolving conflicts on your end — the second time I submitted it I made sure there were no conflicts at the time of submission — so this current conflict came into being sometime after I submitted the Pull Request but before you guys could merge the Pull Request into Master.  I can resubmit this change again but is there any way to make sure that it gets merged into Master when there is no conflicts (aka prior to something else being changed in Master that creates a conflict when originally there was no conflict) ??

- Dennis

**Comment by jordanhubbard** [comment]
I'm sorry you're having so many issues with the pull process, Dennis.  This is usually not so difficult, and the file you're currently conflicting with is in no way new or has changed significantly recently, so I'm not sure why the conflict.

I might suggest that some of this is also unfamiliarity with git, however.  Usually one does the fork and then also pulls that fork up to date with the upstream before sending the PR, so you can catch these issues early (or simply fix the conflict and resubmit on your end) - it shouldn't require intervention on our part to do that.  How long have you guys been using git (and github), if I might ask?

**Comment by jceel** [comment]
Dennis,

Try pulling from freenas-build master, then resolving all the conflicts and resubmit pull request. Also, it's a good practice to submit pull requests from a branch. To move to a branch, do eg `git checkout -b Generic 00001b`

**Comment by DennisJensen-OWC** [comment]
First I want to state I am not trying to argumentative as I know this could interpreted as such — I am simply trying to explain what I did in detail — and get an understanding based on your statements of how this could have happened — from what I am understanding it should not have happened

So to best understand this here is what I did step by step:

1) I deleted my previous Fork
2) I deleted my previous Pull directory
3) I did a fresh Fork of Master
4) I did a fresh Clone of the Fork locally
5) I implemented the changes locallly
6) I Pushed the changes back up to my Fork
7) I created the Pull Request from my Fork and Git said there were no conflicts

I did this all in a span of a few hours in hope that I could implement this change without something else changing on Git to create a conflict.

So no where in here was I working with older code (so not sure how doing a Pull on that Fork would of changed anything) or having a chance of (if that file did not change) changing the file that is currently in question.  This goes with the previous situation as well (unless the two files that had a conflict had actually changed this I do not know).  As it appears I am seem to be getting some kind of ghost conflict due perhaps to the type of change I am trying to implement.

As for familiarity with Git — fairly new to the Git world — but have extensive experience with software version control of various types.  Yes this is the first version control that uses the Git paradigm but some of my previous knowledge is still applicable to this type of version control.  Still I am not trying to do anything fancy with Git on purpose.  I figure that until I have a fuller understanding that I would just keep my steps simple and while this requires a bit more work on my end I was hoping that it would make the process flow easier downstream but so far that has not been the case.

So any incite as to what might be causing the issue would be greatly appreciated.

As it stands I will again try to implement the above steps and hope that the new submission will carry through.

**Comment by justinclift** [comment]
@jordanhubbard The conflict seems to be with https://github.com/freenas/freenas-build/commit/af955651ff0d55d5e8471b49638befb990c4d7fa, which was also changed yesterday.  Oops?

**Comment by jordanhubbard** [comment]
Yes, there is a conflict now, but that can be easily rectified by doing another pull before [re]submitting the PR.

**Comment by justinclift** [comment]
Hmmm yeah, just tried it locally here with a clone of Dennis's branch and the merge succeeded.  It's not pretty, but it didn't fail.

**Pull request closed without merging**
