### PR TITLE
Add FreeBSD revision number that is known to build FN-9.10 these days.

### PR DESCRIPTION
**Pull request by raheelh**
Add FreeBSD revision number that is known to build FN-9.10 these days.

### CODE REVIEW

**Comment by william-gr** [comment]
To me that reads as "use this exact version", perhaps we should note greater or equal?

**Comment by justinclift** [comment]
Yeah, definitely needs an "or greater" on the end. :smile:

eg:

    ... must be FreeBSD 11-STABLE r313553 or greater.

**Comment by justinclift** [comment]
Hmmm, "or newer" might be clearer too.  Up to you guys. :smile:

**Comment by raheelh** [comment]
Rendered .md file shows "or later" in the same line after the revision number. (In the README.md raw/source file, the "or later" is in the next line). Do we still need to replace it with "or greater"/"or newer"? Let me know please.  Thanks!

**Comment by william-gr** [comment]
I totally missed that.

**Comment by raheelh** [comment]
Thanks, everyone!

**Comment by Spearfoot** [comment]
FWIW, I installed the oldest FreeBSD 11.0-STABLE I could find (r309771 dated 10 Dec 2016) and it builds FreeNAS 9.10 successfully. I'm building FN 10 as I write this - it'll be a couple of hours before it finishes - but I have a feeling it will succeed. So I believe we'll be able to safely say ' any version of FreeBSD 11.0-STABLE (r309771) or later' in the **readme**. Will report back when the build finishes...

Just getting my OCD/perfectionist freak on! Ha

**Comment by Spearfoot** [comment]
Okay, checking back in to report that the FN10 build completed successfully and so we can confidently state that FreeBSD 11.0-STABLE #0 r309771 and later versions can be used to build both FreeNAS 9.10 and 10.

**Comment by raheelh** [comment]
Thanks, @Spearfoot ! Pull request has been created to update the revision number.

**Pull request merged**
