### PR TITLE
FIX-GENERIC-00001

### PR DESCRIPTION
**Pull request by DennisJensen-OWC**
These are basically the same changes that were submitted/merged to FreeNAS9-STABLE and were pre approved by Jordan Hubbard and requested that I make a Pull Request against Master with these changes.  The only difference in this change is due to a minor difference between FreeNAS 9.10-STABLE and FreeNAS Master in regards to the presence of FreeNAS 10  /release/.. directory which did not exist before

### CODE REVIEW

**Comment by justinclift** [comment]
Hmmm, weirdly the rename of the BETA2/ReleaseNotes.txt file is causing issues. 😦

**Comment by DennisJensen-OWC** [comment]
Yes I noticed that this would be an issue when I saw it.  It is because in several places they have hard-coded the path to be RELEASE rather than BETA2 if they simply change it back to RELEASE it will fix things until that aspect can be made more generic.  Something my next Pull Request actually addresses just waiting for the previous Pull Request to Master to be closed so that I can submit the next one.

**Comment by justinclift** [comment]
Yeah... I don't think his Pull Request *can* be merged until something is done about the filename conflict.

It might need things to be done in a slightly different order, to work around the problem. :wink:

**Comment by jordanhubbard** [comment]
OK, do you want us to close it or to merge it and then you’ll correct it on another submission, or … ?

**Comment by DennisJensen-OWC** [comment]
Yes if you could merge and close the current Pull Request then I can submit the next one.  Note the next one does not solve the generic problem — I simply changed the folder name from BETA2 back to RELEASE and I did not see any filename conflicts since the code does not reference the “Build” like it maybe should but simply hard-codes the value BETA2 meaning changing to a hard-coded RELEASE should create no issues.

Note my change also fixes some of the folder structure instead of Version - Product - Build I remapped it to Product - Version - Build as a Build belongs to a Version which in turn belongs to a Product — minor perhaps but more intuitive I think.

**Pull request closed without merging**
