### PR TITLE
Updating FreeBSD revision number that is known to build FN-9.10 these days.

### PR DESCRIPTION
**Pull request by raheelh**
Updating document to say "FreeBSD 11-STABLE #0 r309771". Thanks, @Spearfoot, for verifying.

### CODE REVIEW

**Comment by justinclift** [comment]
It'd probably be better to drop the `#0` bit in the line, as it's kind of confusing. :smile:

**Comment by raheelh** [comment]
Removed #0 from revision number, @justinclift.

**Comment by justinclift** [comment]
Awesome @raheelh.  Looks good to me. :smile:

**Comment by justinclift** [comment]
Out of curiosity, have either of you tried running a local version of the new FreeNAS 10 GUI with a remote server?

eg: as in the instructions [for the GUI repo](http://localhost:3000/#?host=freenas.local)

Haven't tried it myself yet, but it looks simple enough and we might be able to get IB stuff into the GUI in time for FreeNAS 10 release. :wink:

(And yeah, not sure if @Spearfoot is interested in IB stuff)

**Comment by Spearfoot** [comment]
Heh. I'm interested in Infiniband -- that's what you mean by 'IB', right? -- but neither of my FreeNAS servers has a free PCIe x8 slot for a card!  :-(

**Comment by justinclift** [comment]
Yep, IB == Infiniband. :smile:

**Comment by raheelh** [comment]
I'll have some time to experiment today.

FreeNAS version I am running is 9.10 FreeNAS-9.10.2-U1 (86c7ef5), which holds all family pictures and videos. It is currently on stock STABLE train.

@justinclift, I never tried FreeNAS 10. Always wondered if FN-10 is stable yet for my use? Do you prefer FN-10 for my IB experimentation?

Otherwise this is what I'm thinking of doing:

- Move to FN-9.10 nightly train. Try out latest nightly with my Mellanox card and see if I can get 10GbE work.

- Try out locally built FN-9.10 with these changes for IB:

```
diff --git a/build/profiles/freenas9/config.pyd b/build/profiles/freenas9/config.pyd
index 06c40e9..f3448e0 100644
--- a/build/profiles/freenas9/config.pyd
+++ b/build/profiles/freenas9/config.pyd
@@ -71,15 +71,15 @@ kernel_modules = [
     "cxgbe",
     "dummynet",
     "hwpmc",
+    "ipoib",
+    "mlx4ib",
+    "mlxen",
+    "mthca",
 ]
 
 if PRODUCT == "TrueNAS":
     kernel_modules += [
         "syscons/blank",
-        "ipoib",
-        "mlx4ib",
-        "mlxen",
-        "mthca"
     ]
 else:
     kernel_modules += [
diff --git a/build/profiles/freenas9/kernel/FREENAS.amd64 b/build/profiles/freenas9/kernel/FREENAS.amd64
index 5de0037..ef689e4 100644
--- a/build/profiles/freenas9/kernel/FREENAS.amd64
+++ b/build/profiles/freenas9/kernel/FREENAS.amd64
@@ -23,6 +23,7 @@ ident		FREENAS64
 
 makeoptions	DEBUG=-g		# Build kernel with gdb(1) debug symbols
 makeoptions	WITH_CTF=1		# Run ctfconvert(1) for DTrace support
+makeoptions     WITH_MK_OFED=1
 
 options 	SCHED_ULE		# ULE scheduler
 options 	PREEMPTION		# Enable kernel thread preemption
@@ -214,6 +215,8 @@ device		ixv			# Intel PRO/10GbE PCIE VF Ethernet
 device		ixl			# Intel XL710 40Gbe PCIE Ethernet
 device		ixlv			# Intel XL710 40Gbe VF PCIE Ethernet
 device		le			# AMD Am7900 LANCE and Am79C9xx PCnet
+device          mlxen
+device          mlx4ib
 device		mlx5			# Mellanox ConnectX-4 common code
 device		mlx5en			# Mellanox ConnectX-4 Series
 device		mxge			# Myricom Myri10GE 10 Gigabit Ethernet adapter driver
```

**Comment by justinclift** [comment]
@raheelh Hmmm, FN10 is probably not going to be stable enough for actual use.

Personally, I'd wait for official FreeNAS 10.0.1 or similar, before sticking real data on it, because I'm paranoid about data integrity. :smile:

Still, it'd be interesting to try it out from the point of view of seeing if your card detects it ok.

With your model card though, the standard everyday FreeNAS you're already running ***should*** detect it.  One potential caveat does spring to mind though...

Any idea which firmware revision is on your card?  If it's really old, that might be the problem.  There was another person on the FreeNAS forums a while ago who had trouble with his older firmware cards not being detected.  After flashing it to the most recent available one (not super difficult), it worked properly. :smile:

---

With that first patch, I'm not sure it'll work.  The `ipoib` line needs to be included as an ***options***:

    options 	IPOIB

...not as a ***device***:

    device 	IPOIB

If the config.pyd entries don't get the right type in there, I'm guessing it'll be ignored.

The mlx4ib line should work though.

---

I'd go with just changing things in the kernel/FREENAS.amd64 file instead, as per your 2nd patch.  But remember to include the ipoib line, if it's not already in the file at the time.

Reference entries, in case they help:

* https://github.com/freebsd/freebsd/blob/bfbc894252b7fe32a42214078724e3b618e5484c/sys/amd64/conf/NOTES#L118
* https://github.com/freebsd/freebsd/blob/bfbc894252b7fe32a42214078724e3b618e5484c/sys/amd64/conf/NOTES#L345

---

Hopefully some of the above helps. 😀

**Comment by raheelh** [comment]
@justinclift, You're right! After flashing newer Mellanox firmware FW 2.9.1000, both the interfaces on the card take IP address just fine in ethernet mode, all this with stock FN-9.10.2-U1 (86c7ef5) (STABLE train) as you suspected! Wahooo! It used to crash when it had older firmware - with same OS.

**Comment by jordanhubbard** [comment]
Can you guys maybe take this to the forum? :)  Pull requests are generally not an ideal "discussion medium" since everyone gets notified on every single change, and I suspect IB is definitely **not** of general interest to the entire development team.

**Comment by justinclift** [comment]
Gah, sorry.  Will do.  @raheelh If you need more discussion for this topic (sound like it's done though), PM me on the forum. Username == `justinclift`.

**Comment by justinclift** [comment]
@jordanhubbard Note - This was a PR, not an issue.  It's probably useful to merge. :wink:

**Pull request merged**
