### PR TITLE
9.10 stable Generic 00001

### PR DESCRIPTION
**Pull request by DennisJensen-OWC**
Okay finally found out how to do a proper Pull Request please delete my previous one.

These are the changes that @jordanhubbard has already approved, I would have included Jakub Klama but could not find him on the contributors list.  I have more changes but I figured getting this small implemented gets things moving in a more Generic direction and is a good test bed for figuring out how to get this collaboration process working.

Sincerely
Dennis Jensen
Lead Software Engineer
Other World Computing

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Adding Jakub (github username jceel)

**Comment by justinclift** [comment]
Cool, this looks like it'll be more obvious how to customise things. :smile:

**Comment by jordanhubbard** [comment]
Ah, I didn't realize that this was directly against freenas:9.10-STABLE instead of the master branch, so assigning to Vaibhav since he's the release engineer who owns that branch.

**Comment by vaibhav-rbs** [comment]
merging pull request #13 with 9.10-STABLE.

**Pull request merged**
